### ISSUE TITLE
Logging behavior for re-running tests

### ISSUE THREAD

**Issue by zjgarvey** [nod-ai/SHARK-TestSuite#124]
Re running tests to debug issues can sometime be a bit confusing.

Let's say, for example, you are getting an iree-compile error on a test, so you make some changes to either the test or a torch-mlir build, and then it gives a torch-mlir error instead. The log folder would then continue to hold the old iree-compile error log despite not getting that far in the pipeline on the most recent run. 

It might be beneficial to have run.py first remove old logs before repopulating the log folder. @ScottTodd @kumardeepakamd do you have any feelings about that kind of change?

**Comment by ScottTodd** [comment]
A few ideas:

* If the logs are small, could keep them around but include a run number and/or timestamp in file or directory names
* Could add a flag to clear outputs and/or logs. Either new options or leverage the existing `--cleanup`: https://github.com/nod-ai/SHARK-TestSuite/blob/73dcb4239cea621e4d5366b04f2bde7ffccd4470/e2eshark/run.py#L1384-L1389

**Comment by zjgarvey** [comment]
Yeah, those ideas sound good. I'll fiddle around with adding a flag for refreshing the log folder. (--refresh would probably work).
