### ISSUE TITLE
Protect main branch

### ISSUE THREAD

**Issue by renxida** [nod-ai/SHARK-TestSuite#177]
@kumardeepakamd we might wanna protect the main branch from direct pushes (and require PRs in order to modify main instead)

I just accidentally pushed to main, and thankfully there wasn't any disruption.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule

**Comment by ScottTodd** [comment]
Added branch protection rule for `main`. LMK if it gets in the way and we can reconfigure.
