### ISSUE TITLE
Phase names and log names inconsistent

### ISSUE THREAD

**Issue by renxida** [nod-ai/SHARK-TestSuite#46]
The name of the phases should be consistent with the names of the log files.

**Comment by renxida** [comment]
e.g. phase onnx-import has its log file called torch-onnx.log.

**Comment by kumardeepakamd** [comment]
https://github.com/nod-ai/SHARK-TestSuite/pull/73 
Good observation, thanks for reporting, uses current phase name now.

**Comment by kumardeepakamd** [comment]
Fixed it. Please check.
