### ISSUE TITLE
Scripts should support installed packages, not just build directories

### ISSUE THREAD

**Issue by ScottTodd** [nod-ai/SHARK-TestSuite#49]
Code like this should be generalized: https://github.com/nod-ai/SHARK-TestSuite/blob/a2aef2b1ca7293600464ab32624fbc4aac717279/e2eshark/run.py#L425-L428 https://github.com/nod-ai/SHARK-TestSuite/blob/a2aef2b1ca7293600464ab32624fbc4aac717279/e2eshark/run.py#L844-L848

Properly installed `iree-compiler` and `iree-runtime` packages from pip can just put console scripts on `$PATH`. Checking `$PATH` first would be a good default, then configuration via flags or environment variables could override if needed.

For developers iterating on tests, the tests could be exported out of Python, the scripts could point at locally built tools, or developers can build Python packages and install them locally (e.g. with https://github.com/openxla/iree/tree/main/build_tools/python_deploy).

**Comment by ScottTodd** [comment]
I'm also not sure why a torch_mlir build is needed... are there equivalent Python APIs or console scripts there? For this sort of test suite to be used on CI it should operate on release artifacts directly.

**Comment by ScottTodd** [comment]
I still see a requirement to build torch-mlir from source. That should be replaced with a pip-installable package (turbine?)

**Comment by stellaraccident** [comment]
There shouldn't be any run/test time dependency on a torch mlir python package.

I've only looked briefly at the above, but I think there is a missing helper class... Something like `ToolHelper` for invoking the various importers. There should be a switch or env var there to control which tools get used if there is a desire to support raw torch mlir dev tooling.

**Comment by ScottTodd** [comment]
Yeah, I'm spinning here trying to get a compatible torch-mlir build on my Windows machine (such that `import torch_mlir` works). I mainly want to export .mlir files (and ideally input/output .npy files) from https://github.com/nod-ai/SHARK-TestSuite/tree/main/e2eshark/pytorch/models, but needing to balance local builds juuuust right is a time sink.

**Comment by ScottTodd** [comment]
Similarly, these deps should be included directly in requirements files, not sourced from another repo:

https://github.com/nod-ai/SHARK-TestSuite/blob/5caa805f5b729e66414546253795b39ca9c14f32/e2eshark/README.md?plain=1#L125-L132

**Comment by stellaraccident** [comment]
> Yeah, I'm spinning here trying to get a compatible torch-mlir build on my Windows machine (such that `import torch_mlir` works). I mainly want to export .mlir files (and ideally input/output .npy files) from https://github.com/nod-ai/SHARK-TestSuite/tree/main/e2eshark/pytorch/models, but needing to balance local builds juuuust right is a time sink.

Don't. We don't support deployment of torch-mlir as an independent thing (and aren't going to). There are some community builds of it, but it is outside of the sphere of things I curate.

**Comment by ScottTodd** [comment]
Yep, I just got through the issues... took longer than I'd like though -- and not something I want to repeat as versions are bumped.

```
D:\dev\projects\SHARK-TestSuite\e2eshark (iree-model-tests)
(.venv) λ python run.py --cachedir D:\dev\scratch\e2eshark -c D:\dev\projects\torch-mlir\build -i D:\dev\projects\iree-build --tests pytorch/models/resnet50 --mode direct
Cache Directory: D:\dev\scratch\e2eshark
Starting e2eshark tests. Using 4 processes
Torch MLIR build: D:\dev\projects\torch-mlir\build
IREE build: D:\dev\projects\iree-build
Test run directory: D:\dev\projects\SHARK-TestSuite\e2eshark\test-run
Since --tests or --testsfile was specified, --groups ignored
Framework:pytorch mode=direct backend=llvm-cpu runfrom=model-run runupto=inference
Test list: ['pytorch/models/resnet50']
Test pytorch/models/resnet50 failed [inference]

Completed run of e2e shark tests

If using the upload feature, you can find a map of the test name to azure urls for your uploaded artifacts in upload_urls.json

D:\dev\projects\SHARK-TestSuite\e2eshark (iree-model-tests)
(.venv) λ ls D:\dev\projects\SHARK-TestSuite\e2eshark\test-run\pytorch\models\resnet50
__pycache__/        inference.log          resnet50.default.goldoutput.pt       runmodel.py
commands.log        inference_input.0.bin  resnet50.default.input.pt            time.pkl
commonutils.py@     iree-compile.log       resnet50.default.pytorch.torch.mlir
E2ESHARK_CHECK.pkl  model-run.log          resnet50.default.vmfb
```

failure was this, but I can work with the .mlir and .pt files I think:
```
EXEC @main
D:\dev\projects\iree\runtime\src\iree\vm\invocation.c:95: INVALID_ARGUMENT; input list and function mismatch; expected 160 arguments but passed 1; stack:
```

**Comment by ScottTodd** [comment]
These should also use what is available in pip or files in the test suite repo itself: https://github.com/nod-ai/SHARK-TestSuite/blob/5caa805f5b729e66414546253795b39ca9c14f32/e2eshark/README.md?plain=1#L142-L148

**Comment by ScottTodd** [comment]
This is still an issue. torch-mlir builds are only published for Linux, making this requirements file incompatible with other operating systems: https://github.com/nod-ai/SHARK-TestSuite/blob/02872307b65f15dd2a3a8c4e7399b918d42413ef/e2eshark/requirements.txt#L15-L16

torch-mlir as a standalone project should not be a requirement for running tests through turbine, onnx, direct pytorch, etc.

**Comment by ScottTodd** [comment]
Aaaah and many model.py files copy/pasted `import torch_mlir` without ever actually using anything from it...

**Comment by ScottTodd** [comment]
Removed the unused imports and updated some docs with workarounds: https://github.com/nod-ai/SHARK-TestSuite/tree/main/iree_tests#pytorch-models

Good enough for me at the moment.
